version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - sam build
      - export BUCKET=b--1
      - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
  post_build:
    commands:
      - aws lambda update-function-code --function-name  index-photos --s3-bucket $BUCKET --s3-key Build.zip   
artifacts:
  files:
    - template.yml
    - outputtemplate.yml
